#This is python code to display "hello world" massege
print("hello world")
print("Foss practical on GitHub")
print("hello world")
print("Foss practical on GitHub")
print("hello world")
print("Foss practic on GitHub")
print("hello world")
print("Foss practical on GitHub")
print("hello world")
print("Foss practical on GitHub")
print("hello world")
print("Foss practic on GitHub")
